name: Build the SDK with tests

permissions:
  checks: write
  pull-requests: write

on:
    push:
      branches:
        - master
        - staging
    pull_request:
      branches:
        - master
        - staging

jobs:
  build:
    name: Run test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -project Countly.xcodeproj -scheme CountlyTests -sdk macosx14.5 test